### ISSUE TITLE
sending multiple fee denoms no longer working since broadcast change

### ISSUE THREAD

**Issue by StrathCole** [coinhall/cosmes#48]
Since the change of the broadcast method, it is no longer possible to send multiple fee denoms via Station extension.

It works with the version pre change.
Issue seems to be that the resulting txRaw returned by extension does only contain one fee denom, further ones are gone.
When sending the tx directly via the old method, everything is handled correctly.

For Terra classic this leads to non functional transactions when they incur fee and tax in different denoms.

**Comment by AaronCQL** [comment]
Closing this issue as this is a bug on Station's end - we will report this bug to the Station team.

**Comment by AaronCQL** [comment]
The Station team already has already fixed this issue on their end, but it's pending their deployment cycle. Not sure when they'll release the fix, but hopefully it is soon. Meanwhile, if you'd like to avoid the issue, you could just use the earlier version which doesn't use the Keplr interface
