### ISSUE TITLE
Error handling for station not always working

### ISSUE THREAD

**Issue by StrathCole** [coinhall/cosmes#49]
The error normalizing misses some TFL station stuff.

```
if (typeof err === "object" && (err as any).error && typeof (err as any).error === "string") {
        throw new Error((err as any).error);
      }
      if (typeof err === "object" && (err as any).error && typeof (err as any).error === "object") {
        throw new Error((err as any).error.message || JSON.stringify(err));
      }
```
      
It might be that `(err as any).error` is not a string and such the current function just returens [object]
      
so adding the above checks solves that

**Comment by AaronCQL** [comment]
@StrathCole do you happen to know a reproducible way to make Station throw such an error?

**Comment by AaronCQL** [comment]
> Sadly the "error code 3" is very generic and covers many different things. As you can see, "error" property of the object is an object itself, so your current handling cannot deal with it. I think station mobile also returns that kind of object.

If the error thrown is an object itself, it should already be handled for by this line, where the object is stringified: https://github.com/coinhall/cosmes/blob/944db2452294852352a153a624e47d0a02255877/src/wallet/wallets/keplr/KeplrExtension.ts#L120

**Comment by AaronCQL** [comment]
> Maybe a custom Error object from the cosmes library that has fields like "message", "code" and "raw" (with the latter holding the original error) so the dApp can decide how to handle the error.

Indeed this would be the best approach. Would you like to contribute to this?

**Comment by AaronCQL** [comment]
closed in https://github.com/coinhall/cosmes/commit/9693198a01e87afc0547dfd0098ceed0050a53cd
