### ISSUE TITLE
Can't verify bytes using commonJS modules in NodeJs.

### ISSUE THREAD

**Issue by przmyst** [coinhall/cosmes#51]
I couldn't get the verify bytes functions working in NodeJs, so I created a standalone function for verifying. The issue with ESM modules is the version of @noble/secp256k1. I rolled back to ^1.7.1 and it works. Hopefully useful for someone.

https://github.com/przmyst/cosmes-verify-keplr-node

**Comment by AaronCQL** [comment]
Do you have a minimal reproducible repo that causes the error mentioned? But do note that cosmes itself isn't tested to be working with commonjs as it is a pure ESM package and the published package only contains ESM code, not commonjs.

**Comment by przmyst** [comment]
Any attempt to use require statement fails.
`const { MsgExecuteContract } = require('cosmes/client')`

**Comment by AaronCQL** [comment]
`require` statements wouldn't work. This package is compiled into ESM only, and it's best to use `import` statements:

```ts
import { MsgExecuteContract } from "cosmes/client";
```

**Comment by o-az** [comment]
To use an ESM package in a CommonJS project you can try dynamically importing it:
```ts
async function main() {
	const { MsgExecuteContract } = await import('cosmes/client')
	// etc.
}
```
A better option would be to abandon CJS and migrate fully to ESM.

**Comment by AaronCQL** [comment]
Closing as commonjs is explicitly not in scope of this project for now.

**Comment by VirtualWizzard** [comment]
hi
