### ISSUE TITLE
Can we add an example of token transfer (or any send any tx)

### ISSUE THREAD

**Issue by llllllluc** [coinhall/cosmes#53]
I tried to do a token transfer but [`signAndBroadcastTx`](https://github.com/coinhall/cosmes/blob/main/src/wallet/wallets/mnemonic/MnemonicWallet.ts#L150) needs me to set `fee`, `accountNumber` and `sequence` manually, is there a way to let cosmes get those for me like cosmjs and featherjs?

**Comment by AaronCQL** [comment]
The `signAndBroadcastTx` isn't meant to be used directly. You'd want to use `broadcastTx` or `broadcastTxSync` depending on your use case. All wallets (including `MnemonicWallet`) will have the `ConnectedWallet` interface, and there's an [example app](https://github.com/coinhall/cosmes/blob/main/examples/solid-vite/src/App.tsx) showing how to broadcast a tx using an instance of `ConnectedWallet`:  

https://github.com/coinhall/cosmes/blob/5b763f6f390700a1fc97d9a8e3dbd1b623842e3f/examples/solid-vite/src/App.tsx#L220-L261

**Comment by llllllluc** [comment]
Ah I see, thanks!
